sonar.projectKey=swirlit:travelmapster
sonar.projectName=TravelMapster
sonar.sourceEncoding=UTF-8
sonar.sources=src,public/js,public/index.html,public/styles.css
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,public/data/**,public/vendor/**
sonar.scm.provider=git
