apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-travelmapster-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app: travelmapster
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infra
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 3000
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infra
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: 9464
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gitlab-runners
          podSelector:
            matchLabels:
              app: gitlab-ci-job
      ports:
        - protocol: TCP
          port: 3000
